# Generated by Django 5.1.15 on 2026-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_can_manage_finance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ars_tier_percent',
            field=models.PositiveSmallIntegerField(choices=[(1, '1%'), (3, '3%'), (5, '5%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%')], default=5, help_text='User-specific ARS revenue tier percentage. Defaults to global setting if not set.'),
        ),
    ]
