# Generated by Django 5.1.15 on 2026-02-10 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('locations', '0002_alter_county_options_alter_state_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='caseactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='casefollowup',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('TD', 'Tax Deed'), ('TL', 'Tax Lien'), ('SS', 'Sheriff Sale'), ('MF', 'Mortgage Foreclosure')], max_length=8),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='locations.county'),
        ),
        migrations.AlterField(
            model_name='case',
            name='parcel_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='property_address',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='caseactionlog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
