# Generated by Django 5.1.15 on 2026-02-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prospect_type', models.CharField(choices=[('TD', 'Tax Deed'), ('TL', 'Tax Lien'), ('SS', 'Sheriff Sale'), ('MF', 'Mortgage Foreclosure')], max_length=8)),
                ('min_surplus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('status_types', models.JSONField(blank=True, default=list)),
                ('auction_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.county')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.state')),
            ],
            options={
                'ordering': ('-is_active', 'state__name', 'county__name', 'name'),
            },
        ),
    ]
