# Generated by Django 5.1.15 on 2026-02-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtercriteria',
            options={'ordering': ['-is_active', 'state__name', 'county__name', 'name'], 'verbose_name_plural': 'filter criteria'},
        ),
    ]
