# Generated by Django 5.1.15 on 2026-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_filtercriteria_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtercriteria',
            name='min_surplus_amount',
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='assessed_value_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum assessed property value', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='assessed_value_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum assessed property value', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='final_judgment_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum final judgment amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='final_judgment_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum final judgment amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='plaintiff_max_bid_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum plaintiff maximum bid amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='plaintiff_max_bid_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum plaintiff maximum bid amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='sale_amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum sale amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='sale_amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum sale amount', max_digits=14, null=True),
        ),
    ]
