# Generated by Django 5.1.15 on 2026-02-12 12:00

from django.db import migrations, models


def copy_legacy_fields(apps, schema_editor):
    FilterCriteria = apps.get_model('settings_app', 'FilterCriteria')
    for rule in FilterCriteria.objects.all():
        updated = False
        if rule.prospect_type and not rule.prospect_types:
            rule.prospect_types = [rule.prospect_type]
            updated = True
        if updated:
            rule.save(update_fields=['prospect_types'])
        if rule.county_id:
            rule.counties.add(rule.county_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_county_options_alter_state_options_and_more'),
        ('settings_app', '0003_remove_filtercriteria_min_surplus_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtercriteria',
            options={'ordering': ['-is_active', 'state__name', 'name'], 'verbose_name_plural': 'filter criteria'},
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='counties',
            field=models.ManyToManyField(blank=True, related_name='filter_criteria_rules', to='locations.county'),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='prospect_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='sold_to',
            field=models.CharField(blank=True, default='', help_text="Match exact 'Sold To' value", max_length=255),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='surplus_amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum surplus amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='filtercriteria',
            name='surplus_amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum surplus amount', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='filtercriteria',
            name='prospect_type',
            field=models.CharField(blank=True, choices=[('TD', 'Tax Deed'), ('TL', 'Tax Lien'), ('SS', 'Sheriff Sale'), ('MF', 'Mortgage Foreclosure')], max_length=8),
        ),
        migrations.RunPython(copy_legacy_fields, noop_reverse),
    ]
