# Generated by Django 5.1.15 on 2026-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_ssrevenuesetting_ars_tier_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssrevenuesetting',
            name='surplus_threshold_1',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='First surplus threshold (e.g., Less than $50,000)', max_digits=12),
        ),
        migrations.AddField(
            model_name='ssrevenuesetting',
            name='surplus_threshold_2',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='Second surplus threshold (e.g., Less than $100,000)', max_digits=12),
        ),
        migrations.AddField(
            model_name='ssrevenuesetting',
            name='surplus_threshold_3',
            field=models.DecimalField(decimal_places=2, default=150000, help_text='Third surplus threshold (e.g., Less than $150,000)', max_digits=12),
        ),
    ]
