# Generated by Django 5.1.15 on 2026-02-09 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('fips_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('available_prospect_types', models.JSONField(blank=True, default=list)),
                ('uses_realtdm', models.BooleanField(default=False)),
                ('uses_auction_calendar', models.BooleanField(default=False)),
                ('auction_calendar_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('realtdm_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('foreclosure_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('taxdeed_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('platform', models.CharField(choices=[('realforeclose', 'realforeclose'), ('realtaxdeed', 'realtaxdeed'), ('other', 'other')], default='other', max_length=32)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='locations.state')),
            ],
            options={
                'unique_together': {('state', 'slug')},
            },
        ),
    ]
