# Generated by Django 5.1.15 on 2026-02-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name_plural': 'counties'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='county',
            name='auction_calendar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='county',
            name='fips_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='county',
            name='foreclosure_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='county',
            name='platform',
            field=models.CharField(choices=[('realforeclose', 'RealForeclose'), ('realtaxdeed', 'RealTaxDeed'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='county',
            name='realtdm_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='county',
            name='taxdeed_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
