# Generated by Django 5.1.15 on 2026-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_county_options_alter_state_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='ac_url',
            field=models.URLField(blank=True, default='', help_text='Auction Calendar URL'),
        ),
        migrations.AddField(
            model_name='county',
            name='tdm_url',
            field=models.URLField(blank=True, default='', help_text='Tax Deed Manager URL'),
        ),
    ]
