# Generated by Django 5.1.15 on 2026-02-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_county_ac_url_county_tdm_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='ac_url',
        ),
        migrations.RemoveField(
            model_name='county',
            name='available_prospect_types',
        ),
        migrations.RemoveField(
            model_name='county',
            name='foreclosure_url',
        ),
        migrations.RemoveField(
            model_name='county',
            name='taxdeed_url',
        ),
        migrations.RemoveField(
            model_name='county',
            name='tdm_url',
        ),
    ]
