# Generated by Django 5.1.15 on 2026-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_county_ac_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='uses_auction_calendar',
        ),
        migrations.RemoveField(
            model_name='county',
            name='uses_realtdm',
        ),
    ]
