# Generated by Django 5.1.15 on 2026-02-09 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_type', models.CharField(choices=[('TD', 'Tax Deed'), ('TL', 'Tax Lien'), ('SS', 'Sheriff Sale'), ('MF', 'Mortgage Foreclosure')], max_length=8)),
                ('auction_item_number', models.CharField(blank=True, max_length=100)),
                ('case_number', models.CharField(max_length=200)),
                ('case_style', models.CharField(blank=True, max_length=255)),
                ('property_address', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('parcel_id', models.CharField(blank=True, max_length=200)),
                ('final_judgment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opening_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('plaintiff_max_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('surplus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('auction_date', models.DateField(blank=True, null=True)),
                ('auction_time', models.TimeField(blank=True, null=True)),
                ('auction_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('sold_third_party', 'Sold Third Party'), ('sold_plaintiff', 'Sold Plaintiff'), ('postponed', 'Postponed'), ('struck_off', 'Struck Off')], max_length=32)),
                ('qualification_status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified')], default='pending', max_length=32)),
                ('workflow_status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('researching', 'Researching'), ('skip_tracing', 'Skip Tracing'), ('contacting', 'Contacting'), ('contract_sent', 'Contract Sent'), ('converted', 'Converted'), ('dead', 'Dead')], default='new', max_length=32)),
                ('plaintiff_name', models.CharField(blank=True, max_length=255)),
                ('defendant_name', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('legal_description', models.TextField(blank=True)),
                ('certificate_of_title', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('lien_check_done', models.BooleanField(default=False)),
                ('lien_check_notes', models.TextField(blank=True)),
                ('surplus_verified', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('skip_trace_done', models.BooleanField(default=False)),
                ('owner_contact_info', models.TextField(blank=True)),
                ('contact_attempts', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_monitored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_prospects', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='locations.county')),
            ],
            options={
                'unique_together': {('county', 'case_number', 'auction_date')},
            },
        ),
        migrations.CreateModel(
            name='ProspectActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('qualified', 'qualified'), ('disqualified', 'disqualified'), ('assigned', 'assigned'), ('note_added', 'note_added'), ('email_sent', 'email_sent'), ('status_changed', 'status_changed'), ('converted_to_case', 'converted_to_case')], max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='prospects.prospect')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProspectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prospects.prospect')),
            ],
        ),
    ]
