# Generated by Django 5.1.15 on 2026-02-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ('-created_at',)},
        ),
    ]
