# Generated by Django 5.1.15 on 2026-02-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_prospect_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['-auction_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prospectactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prospectnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='prospectnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='auction_item_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='auction_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('sold_third_party', 'Sold Third Party'), ('sold_plaintiff', 'Sold Plaintiff'), ('postponed', 'Postponed'), ('struck_off', 'Struck Off')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='case_style',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='certificate_of_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='defendant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='legal_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='lien_check_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='owner_contact_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='parcel_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='plaintiff_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='property_address',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='property_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospectactionlog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('assigned', 'Assigned'), ('note_added', 'Note Added'), ('email_sent', 'Email Sent'), ('status_changed', 'Status Changed'), ('converted_to_case', 'Converted to Case')], max_length=64),
        ),
        migrations.AlterField(
            model_name='prospectactionlog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProspectEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='prospects.prospect')),
                ('recipients', models.ManyToManyField(related_name='received_prospect_emails', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_prospect_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
