# Generated by Django 5.1.15 on 2026-02-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_alter_prospect_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='auction_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
