# Generated by Django 5.1.15 on 2026-02-14 00:55

import apps.prospects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0007_rename_rule_note_and_add_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='auction_status',
            field=models.CharField(blank=True, choices=[('Canceled per Bankruptcy', 'Canceled per Bankruptcy'), ('Canceled per County', 'Canceled per County'), ('Canceled per Order', 'Canceled per Order'), ('Other', 'Other'), ('Redeemed', 'Redeemed'), ('Sold', 'Sold')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='ProspectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.prospects.models.prospect_document_upload_to)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='prospects.prospect')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
