# Generated by Django 5.1.15 on 2026-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0008_prospect_parcel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='auction_status',
            field=models.CharField(blank=True, choices=[('Canceled per Bankruptcy', 'Canceled per Bankruptcy'), ('Canceled per County', 'Canceled per County'), ('Canceled per Order', 'Canceled per Order'), ('Other', 'Other'), ('Redeemed', 'Redeemed'), ('Sold', 'Sold')], default='', max_length=32),
        ),
    ]
