# Generated by Django 5.1.15 on 2026-02-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0009_alter_prospect_auction_status'),
        ('prospects', '0009_prospectdocumentnote'),
    ]

    operations = [
    ]
