# Generated by Django 5.1.15 on 2026-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0010_merge_20260214_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='ack_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prospect',
            name='tdm_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
