# Generated by Django 5.1.15 on 2026-02-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0013_prospect_disqualification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='source',
            field=models.CharField(blank=True, choices=[('AC', 'Auction Calendar'), ('CU', 'County Upload'), ('CE', 'County Emailed'), ('EE', 'Excess Elite')], default='', max_length=4),
        ),
    ]
