# Generated by Django 5.1.15 on 2026-02-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0015_csvuploadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='uploaded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='prospects.csvuploadlog'),
        ),
    ]
