# Generated by Django 5.1.15 on 2026-02-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0016_prospect_uploaded_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectTDMDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50)),
                ('case_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('doc_date', models.CharField(blank=True, max_length=100)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('is_auto_download', models.BooleanField(default=False)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('download_error', models.TextField(blank=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_documents', to='prospects.prospect')),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'unique_together': {('prospect', 'document_id')},
            },
        ),
    ]
