# Generated by Django 5.1.15 on 2026-02-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date (inclusive). Leave blank for single date.', null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='target_date',
            field=models.DateField(help_text='Start date for scraping'),
        ),
    ]
