# Generated by Django 5.1.15 on 2026-02-10 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_county_options_alter_state_options_and_more'),
        ('scraper', '0002_scrapejob_end_date_alter_scrapejob_target_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for the job', max_length=255)),
                ('state', models.CharField(default='FL', help_text="State code (e.g., 'FL')", max_length=10)),
                ('county', models.CharField(help_text='County name', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_success', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('custom_params', models.JSONField(blank=True, default=dict, help_text='Custom parameters as JSON')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('task_id', models.CharField(blank=True, help_text='Thread ID or execution identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scraping Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_duration', models.DurationField(blank=True, help_text='Total execution time', null=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, help_text='Thread ID', max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='scraper.scrapingjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('Network', 'Network Error'), ('Parsing', 'Parsing Error'), ('DataValidation', 'Data Validation Error'), ('System', 'System Error')], max_length=32)),
                ('error_message', models.TextField()),
                ('error_traceback', models.TextField(blank=True)),
                ('is_retryable', models.BooleanField(default=True)),
                ('retry_attempt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='scraper.jobexecutionlog')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='scraper.scrapingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserJobDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_start_date', models.DateField(blank=True, null=True)),
                ('last_end_date', models.DateField(blank=True, null=True)),
                ('last_custom_params', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.county')),
                ('default_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Job Defaults',
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='CountyScrapeURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this URL')),
                ('county', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_url', to='locations.county')),
                ('state', models.ForeignKey(help_text='Quick reference to state', on_delete=django.db.models.deletion.CASCADE, related_name='county_scrape_urls', to='locations.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'County Scrape URLs',
                'unique_together': {('county',)},
            },
        ),
    ]
