# Generated by Django 5.1.15 on 2026-02-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_county_options_alter_state_options_and_more'),
        ('scraper', '0003_scrapingjob_jobexecutionlog_joberror_userjobdefaults_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countyscrapeurl',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='countyscrapeurl',
            name='url_type',
            field=models.CharField(choices=[('TD', 'Tax Deed'), ('TL', 'Tax Lien'), ('SS', 'Sheriff Sale'), ('MF', 'Mortgage Foreclosure')], default='MF', help_text='Job type this URL is for', max_length=8),
        ),
        migrations.AlterField(
            model_name='countyscrapeurl',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_urls', to='locations.county'),
        ),
        migrations.AlterUniqueTogether(
            name='countyscrapeurl',
            unique_together={('county', 'url_type')},
        ),
    ]
