# Generated by Django 5.1.15 on 2026-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_scrapejob_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyscrapeurl',
            name='ac',
            field=models.BooleanField(default=False, help_text='AC (Assessment Certificate) enabled'),
        ),
        migrations.AddField(
            model_name='countyscrapeurl',
            name='ac_url',
            field=models.URLField(blank=True, help_text='URL for AC resources', null=True),
        ),
        migrations.AddField(
            model_name='countyscrapeurl',
            name='tdm',
            field=models.BooleanField(default=False, help_text='TDM (Tax Deed Market) enabled'),
        ),
        migrations.AddField(
            model_name='countyscrapeurl',
            name='tdm_url',
            field=models.URLField(blank=True, help_text='URL for TDM resources', null=True),
        ),
    ]
