# Generated by Django 5.1.15 on 2026-02-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_countyscrapeurl_ac_countyscrapeurl_ac_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyscrapeurl',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='countyscrapeurl',
            name='ac_url',
        ),
        migrations.RemoveField(
            model_name='countyscrapeurl',
            name='tdm',
        ),
        migrations.RemoveField(
            model_name='countyscrapeurl',
            name='tdm_url',
        ),
    ]
